# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'poiDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for poiDemo

  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RxSwiftExt', '~> 5'
  pod 'RxDataSources', '~> 4.0'

#高德地图
  pod 'AMapLocation', '~> 2.6.7'
  pod 'AMapSearch', '~> 6.9.0'
  pod 'AMapNavi', '~> 7.7.1'

  pod 'MBProgressHUD', '~> 1.2.0'

  pod 'YogaKit', '~> 1.7'

# 常用UIkit 扩展 方便使用
  pod 'YYCategories', '~> 1.0.4'



end
